// Code generated by protoc-gen-go.
// source: demo.proto
// DO NOT EDIT!

/*
Package demo is a generated protocol buffer package.

It is generated from these files:
	demo.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	CreateTodoRequest
	CreateTodoResponse
	Todo
*/
package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateTodoRequest struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *CreateTodoRequest) Reset()                    { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()               {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateTodoRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type CreateTodoResponse struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *CreateTodoResponse) Reset()                    { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()               {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type Todo struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Done        bool   `protobuf:"varint,3,opt,name=done" json:"done,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Todo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "demo.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "demo.HelloReply")
	proto.RegisterType((*CreateTodoRequest)(nil), "demo.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "demo.CreateTodoResponse")
	proto.RegisterType((*Todo)(nil), "demo.Todo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/demo.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	out := new(CreateTodoResponse)
	err := grpc.Invoke(ctx, "/demo.Greeter/CreateTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.Greeter/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "CreateTodo",
			Handler:    _Greeter_CreateTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x9b, 0x60, 0xd1, 0x72, 0x45, 0x08, 0x6e, 0xc1, 0xea, 0x80, 0x22, 0x0f, 0xa8, 0x53,
	0x87, 0x94, 0x17, 0x40, 0x0c, 0x30, 0x30, 0x05, 0x5e, 0x20, 0xe0, 0x13, 0x8a, 0x94, 0xf8, 0x8c,
	0x6d, 0x86, 0x6c, 0x3c, 0x3a, 0xca, 0x85, 0x42, 0x50, 0x06, 0xb6, 0xff, 0x7e, 0x7f, 0x67, 0xdf,
	0x7f, 0x06, 0xb0, 0xd4, 0xf1, 0xce, 0x07, 0x4e, 0x8c, 0x6a, 0xd0, 0xc6, 0xc0, 0xe9, 0x03, 0xb5,
	0x2d, 0x57, 0xf4, 0xfe, 0x41, 0x31, 0x21, 0x82, 0x72, 0x75, 0x47, 0x3a, 0x2b, 0xb2, 0xed, 0x49,
	0x25, 0xda, 0x5c, 0x03, 0x7c, 0x33, 0xbe, 0xed, 0x51, 0xc3, 0xb2, 0xa3, 0x18, 0xeb, 0xb7, 0x03,
	0x74, 0x28, 0xcd, 0x1e, 0x2e, 0xee, 0x02, 0xd5, 0x89, 0x9e, 0xd9, 0xfe, 0x5c, 0x78, 0x05, 0x2a,
	0xb1, 0x65, 0x61, 0xd7, 0x25, 0xec, 0x64, 0x02, 0x01, 0xc4, 0x37, 0x37, 0x80, 0xd3, 0xa6, 0xe8,
	0xd9, 0x45, 0xfa, 0xb7, 0xeb, 0x11, 0xd4, 0x50, 0xe1, 0x19, 0xe4, 0x8d, 0x15, 0x4a, 0x55, 0x79,
	0x63, 0xb1, 0x80, 0xb5, 0xa5, 0xf8, 0x1a, 0x1a, 0x9f, 0x1a, 0x76, 0x3a, 0x97, 0x01, 0xa7, 0xd6,
	0x10, 0xd0, 0xb2, 0x23, 0x7d, 0x54, 0x64, 0xdb, 0x55, 0x25, 0xba, 0xfc, 0xcc, 0x60, 0x79, 0x1f,
	0x88, 0x12, 0x05, 0x2c, 0x61, 0xf5, 0x54, 0xf7, 0x92, 0x17, 0x71, 0x7c, 0x77, 0xba, 0xa0, 0xcd,
	0xf9, 0x1f, 0xcf, 0xb7, 0xbd, 0x59, 0xe0, 0x2d, 0xc0, 0x6f, 0x06, 0xbc, 0x1c, 0x89, 0xd9, 0x2a,
	0x36, 0x7a, 0x7e, 0x30, 0xc6, 0x35, 0x8b, 0x97, 0x63, 0xf9, 0x94, 0xfd, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc8, 0x9b, 0xb8, 0x7a, 0xa2, 0x01, 0x00, 0x00,
}
